name: Android CI

permissions:
  contents: read

on: [push]

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace
      - name: Build Bale APK
        run: ./gradlew assembleBale --stacktrace
      - name: Build Snapp APK
        run: ./gradlew assembleSnapp --stacktrace
      - name: Upload APKs
        uses: actions/upload-artifact@v5
        with:
          name: WebAPK
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/bale/*.apk
            app/build/outputs/apk/snapp/*.apk
            
